
# SEO settings
title_left    : "dragon"
title_right   : "power" # default: ""
# description: "给我光明的欺骗，让我一直都向前"
# keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: https://longuan.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: UA-XXXXX-XX
# disqus_shortname: "hnbloggithub"
# twitter_username: "HeiswayiNrird"
comments_enabled  : false
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "longuan"
  # job      : "Software Engineer"
  bio      : "面对大河我无限惭愧 年华虚度 空有一身疲倦"
  thumb    : /assets/images/author.jpg
  email    : beatjean1314@gmail.com
  url      : https://longuan.github.io
  github   : https://github.com/longuan

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  - jekyll-feed

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : links
    title: Links
  - slug : others
    title: Others

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
